name = "Cobblemoon"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83f2a36bddf75da89cc69073c4ff1725aa508ff2980397e15f2371a43a85a751"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
