name = "Cobblemoon"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606499d3e165e2c04e9c8ee91f7084fbe7264884c713da24518cd935cc83f5b2"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
