name = "Cobblemoon"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61513cbd27fea382a06f8f112bb31b23f1a53e668065934fef273f5822d96a37"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
